### ISSUE TITLE
Help DoOR.data::load_door_data() to work

### ISSUE THREAD

**Issue by jefferis** [Dahaniel/DoOR.data#24]
if you changed 
https://github.com/ropensci/DoOR.data/blob/b38198bf3cddf5e9dc558a125e2eeacbb024a620/R/load_door_data.R#L39

to

```
utils::data(list = all.data$results[, 3], package = "DoOR.data")
```
then 
```
DoOR.data::load_door_data()
```
would work even without having the package attached.

**Comment by Dahaniel** [comment]
Thanks for the hint!
